// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Distance {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Distance {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

m():number {
  return this.bb!.readInt16(this.bb_pos);
}

static sizeOf():number {
  return 2;
}

static createDistance(builder:flatbuffers.Builder, m: number):flatbuffers.Offset {
  builder.prep(2, 2);
  builder.writeInt16(m);
  return builder.offset();
}

}
