// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { TestNode } from '../test/test-node';


export class Test {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Test {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTest(bb:flatbuffers.ByteBuffer, obj?:Test):Test {
  return (obj || new Test()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTest(bb:flatbuffers.ByteBuffer, obj?:Test):Test {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Test()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

vec(index: number, obj?:TestNode):TestNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TestNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

vecLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addVec(builder:flatbuffers.Builder, vecOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, vecOffset, 0);
}

static createVecVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVecVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTest(builder:flatbuffers.Builder, vecOffset:flatbuffers.Offset):flatbuffers.Offset {
  Test.startTest(builder);
  Test.addVec(builder, vecOffset);
  return Test.endTest(builder);
}
}
