// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BTreeNode } from '../map-data/b-tree-node';


export class BTreeData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):BTreeData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBTreeData(bb:flatbuffers.ByteBuffer, obj?:BTreeData):BTreeData {
  return (obj || new BTreeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBTreeData(bb:flatbuffers.ByteBuffer, obj?:BTreeData):BTreeData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BTreeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

size():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

maxNodeSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

root(obj?:BTreeNode):BTreeNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new BTreeNode()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startBTreeData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSize(builder:flatbuffers.Builder, size:number) {
  builder.addFieldInt16(0, size, 0);
}

static addMaxNodeSize(builder:flatbuffers.Builder, maxNodeSize:number) {
  builder.addFieldInt8(1, maxNodeSize, 0);
}

static addRoot(builder:flatbuffers.Builder, rootOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, rootOffset, 0);
}

static endBTreeData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
